fix the chinese character generation as same as PR #321
ml-explore/mlx-examples pull request #342
Opened 2024-01-20 08:32 UTC by iLoveBug

It's the same fix as PR #321 as it fixed the code in utils.py, but the function generation is not used in main function.
So I do it once again here.

2024-01-20 10:57 UTC, mzbac commented
Thanks for the PR, but the fix feels a bit repetitive. Would you mind updating the main to use "generate" from utils instead? Personally, I feel that would be a better solution.

2024-01-20 14:03 UTC, awni commented
I agree with @mzbac , but the only difficulty with that is not removing the timing information from the CLI version. Some options:

1. Remove the timing information for the CLI
2. Change utils.py generate to return a dictionary of a result which includes other data/metadata (currently the timing info, but we may add more in the future like probabilities)
3. Always print timing in the utils.py generation (when in VERBOSE mode)


I think it's nice to have the timing information easily there so I like 2 or 3 but I'm also not that opposed to removing it.

2024-01-20 16:14 UTC, iLoveBug commented
It's always a good idea to reduce duplicate code as much as possible. 

I’d like to keep the timing information, and I even print the timing information in lora.py in my local copy so that I can see the total fine-tuning time used.

So I think maybe option 3 is a good idea: print timing information in verbose mode?

> 2024年1月20日 22:04，Awni Hannun ***@***.***> 写道：
> 
> 
> I agree with @mzbac <https://github.com/mzbac> , but the only difficulty with that is not removing the timing information from the CLI version. Some options:
> 
> Remove the timing information for the CLI
> Change utils.py generate to return a dictionary of a result which includes other data/metadata (currently the timing info, but we may add more in the future like probabilities)
> Always print timing in the utils.py generation (when in VERBOSE mode)
> I think it's nice to have the timing information easily there so I like 2 or 3 but I'm also not that opposed to removing it.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/ml-explore/mlx-examples/pull/342#issuecomment-1902103831>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AJYUF74GQA7MWKU57MU6GGLYPPFFDAVCNFSM6AAAAABCDBBYHKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBSGEYDGOBTGE>.
> You are receiving this because you authored the thread.
>

2024-01-22 16:53 UTC, awni commented on llms/mlx_lm/generate.py
> +    parser.add_argument('-v', '--verbose', help='Increase output verbosity', action='store_true')
👍

2024-01-22 16:58 UTC, awni requested changes
Looks great, nice simplification! Just a couple minor changes and then it's good to merge. Thanks for the contribution!

2024-01-22 16:58 UTC, awni commented on llms/mlx_lm/generate.py
> +        print(output)
Let's just fix verbose to `True` for `generate.py`. I don't think anyone will want to use it without verbosity (that's meant more for the API)

2024-01-22 16:58 UTC, awni commented on llms/mlx_lm/generate.py
> +    parser.add_argument('-v', '--verbose', help='Increase output verbosity', action='store_true')
Remove per below comment.

2024-01-22 16:58 UTC, awni commented on llms/mlx_lm/utils.py
> +    seed: int = 0,
Also can you revert to set the seed outside this function (e.g. before you call `generate` in `generate.py`. I think I prefer that to give the caller more control over how to seed the RNG state.

2024-01-23 04:02 UTC, awni commented
Also could you rebase this on main as it appears there is a conflict. Thank you!

2024-01-23 18:52 UTC, awni approved these changes
Thank you looks great!

2024-01-23 20:43 UTC, awni approved these changes
I did some changes here to fix color formatting with this. It should all be mostly good now. But I changed the way we do formatting to a user provided callback to keep the main generation loop simple.

Thanks for the addition.

2024-01-23 20:44 UTC, merged